services:
  - type: web
    name: movie-streaming-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: TMDB_API_KEY
        value: e2fadb339b4f592654086499e9cfc9b1
    autoDeploy: true
    region: oregon